version: '3.8'

services:
  app:
    image: dsypasit/subject_system
    depends_on:
      - mysqldb
    #build:
      #context: test/
    volumes:
      - ./:/app

  mysqldb:
    image: mysql
    ports:
      - 3366:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:
